# Generated by Django 6.0.2 on 2026-02-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_optiongroup_categoryoption_productoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='option_group',
        ),
        migrations.RenameField(
            model_name='productoption',
            old_name='choice',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='price',
        ),
        migrations.AddField(
            model_name='productoption',
            name='choices',
            field=models.JSONField(default=list, help_text='Store choices as a list of name/price pairs, e.g. [{"name": "Large", "price": 3.00}]'),
        ),
        migrations.DeleteModel(
            name='OptionGroup',
        ),
    ]
