# Generated by Django 6.0.2 on 2026-02-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_price_at_time_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('ready', 'Ready'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20),
        ),
    ]
