# Generated by Django 6.0.2 on 2026-02-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='choices',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
