# Generated by Codex on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_dailyclosing'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyclosing',
            name='closing_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyclosing',
            name='opening_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
